# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  TargetRubyVersion: 3.4

Bundler/OrderedGems:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/ClosingHeredocIndentation:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndOfLine:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/CopDirectiveSyntax:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Performance/CompareWithBlock:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/StartWith:
  Enabled: true

Rails/ActionControllerFlashBeforeRender:
  Enabled: true

Rails/ActionControllerTestCase:
  Enabled: true

Rails/ActionOrder:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

Rails/DangerousColumnNames:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/DefaultScope:
  Enabled: true

Rails/DuplicateAssociation:
  Enabled: true

Rails/DuplicateScope:
  Enabled: true

Rails/EnvLocal:
  Enabled: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/IgnoredSkipActionFilterOption:
  Enabled: true

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Rails/SafeNavigation:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true
  Exclude:
    - "db/**/*"

Rails/StrongParametersExpect:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/WhereMissing:
  Enabled: true

Rails/WhereRange:
  Enabled: true

Security/Eval:
  Enabled: true

Security/IoMethods:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/ClassMethodsDefinitions:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/DataInheritance:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/For:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - "db/**/*"

Style/IfInsideElse:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/RescueStandardError:
  Enabled: true

Style/Sample:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets
  Exclude:
    - "db/**/*"
    - "lib/tasks/**/*.rake"

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets
  Exclude:
    - "db/**/*"
    - "lib/tasks/**/*.rake"
